### ISSUE TITLE
How to push edited diagrams

### ISSUE THREAD

**Issue by ludwig-weiss** [structurizr/cloud#7]
I have a diagram, without autolayout which displays perfectly on structurizr-lite

![grafik](https://user-images.githubusercontent.com/59934700/200920497-42faece6-698e-4628-bd09-ec52fe67d9a3.png)

But when I push it to structurizr.com using structurizr-cli it displays like:

![grafik](https://user-images.githubusercontent.com/59934700/200920882-33d0f2e5-2023-4584-87be-d1f66d95ff76.png)

Could you please give me a hint what I am doing wrong here?

**Comment by simonbrowndotje** [comment]
Yes, if you're using manual layout, you'll need to use the CLI to push the `workspace.json` file (this has the layout information), rather than the `workspace.dsl` file. See [Structurizr Lite - 5.1 Structurizr DSL](https://structurizr.com/share/76352/documentation#structurizr-dsl) for more information.

<img width="1267" alt="Screenshot 2022-11-09 at 19 20 57" src="https://user-images.githubusercontent.com/1009874/200921830-5e8f8d72-01fc-4001-8ad4-5cc315842997.png">

**Comment by ludwig-weiss** [comment]
Thank you for the quick answer.
Now that I've added `-merge false` the layout is still not fixed.

I am not sure if I do this correctly.

What I do currently is:

1. fire up structrizr-lite locally (without auto-sync configured)
2. edit `workspace.dsl`
3. Layout manually in structurizr-lite
4. git push to a local gitlab instance (`workspace.dsl` and `workspace.json` not `.structurizr` folder)
5. a gitlab ci job running 
    ```
    structurizr.sh push -merge false -id ${STRUCTURIZR_WORKSPACE} -key ${STRUCTURIZR_KEY} -secret ${STRUCTURIZR_SECRET} -w docs
   ```

Is there any step I am missing here? Or is this workflow not right?

**Comment by ludwig-weiss** [comment]
Ahh, this did the trick. I had the complete folder in the line.
Thank you.
